// <auto-generated />
using System;
using AuthService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuthService.Persistence.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuthService.Domain.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasAlternateKey("Id", "Key")
                        .HasName("ak_applications_id_key");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_applications_key");

                    b.ToTable("applications", null, t =>
                        {
                            t.HasCheckConstraint("ck_applications_key_format", "key ~ '^[a-z][a-z0-9-]{1,62}$'");
                        });
                });

            modelBuilder.Entity("AuthService.Domain.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ApplicationKey")
                        .IsRequired()
                        .HasMaxLength(63)
                        .HasColumnType("character varying(63)")
                        .HasColumnName("application_key");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsObsolete")
                        .HasColumnType("boolean")
                        .HasColumnName("is_obsolete");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("ObsoletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("obsoleted_at");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.HasAlternateKey("ApplicationId", "Id")
                        .HasName("ak_operations_application_id_id");

                    b.HasIndex("ApplicationId", "ApplicationKey")
                        .HasDatabaseName("ix_operations_application_id_application_key");

                    b.HasIndex("ApplicationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_operations_application_id_name");

                    b.ToTable("operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_operations_name_has_application_prefix", "starts_with(name, application_key || '.')");
                        });
                });

            modelBuilder.Entity("AuthService.Domain.OperationImplication", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("ImpliedOperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("implied_operation_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.HasKey("OperationId", "ImpliedOperationId")
                        .HasName("pk_operation_implications");

                    b.HasIndex("ApplicationId", "ImpliedOperationId")
                        .HasDatabaseName("ix_operation_implications_application_id_implied_operation_id");

                    b.HasIndex("ApplicationId", "OperationId")
                        .HasDatabaseName("ix_operation_implications_application_id_operation_id");

                    b.ToTable("operation_implications", null, t =>
                        {
                            t.HasCheckConstraint("ck_operation_implications_not_self", "operation_id <> implied_operation_id");
                        });
                });

            modelBuilder.Entity("AuthService.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasAlternateKey("ApplicationId", "Id")
                        .HasName("ak_roles_application_id_id");

                    b.HasIndex("ApplicationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_application_id_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.RoleOperation", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.HasKey("RoleId", "OperationId")
                        .HasName("pk_role_operations");

                    b.HasIndex("ApplicationId", "OperationId")
                        .HasDatabaseName("ix_role_operations_application_id_operation_id");

                    b.HasIndex("ApplicationId", "RoleId")
                        .HasDatabaseName("ix_role_operations_application_id_role_id");

                    b.ToTable("role_operations", (string)null);
                });

            modelBuilder.Entity("AuthService.Domain.Operation", b =>
                {
                    b.HasOne("AuthService.Domain.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId", "ApplicationKey")
                        .HasPrincipalKey("Id", "Key")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operations_application_id_key");
                });

            modelBuilder.Entity("AuthService.Domain.OperationImplication", b =>
                {
                    b.HasOne("AuthService.Domain.Operation", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId", "ImpliedOperationId")
                        .HasPrincipalKey("ApplicationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operation_implications_implied_same_application");

                    b.HasOne("AuthService.Domain.Operation", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId", "OperationId")
                        .HasPrincipalKey("ApplicationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operation_implications_operation_same_application");
                });

            modelBuilder.Entity("AuthService.Domain.Role", b =>
                {
                    b.HasOne("AuthService.Domain.Application", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_roles_applications_application_id");
                });

            modelBuilder.Entity("AuthService.Domain.RoleOperation", b =>
                {
                    b.HasOne("AuthService.Domain.Operation", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId", "OperationId")
                        .HasPrincipalKey("ApplicationId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_operations_operation_same_application");

                    b.HasOne("AuthService.Domain.Role", null)
                        .WithMany()
                        .HasForeignKey("ApplicationId", "RoleId")
                        .HasPrincipalKey("ApplicationId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_operations_role_same_application");
                });
#pragma warning restore 612, 618
        }
    }
}
